delete from name_email;
insert into name_email set nombre='Jesus', email='je@sus.com', cp = 12345;
insert into name_email set nombre='Pablo', email='pa@blo.com';
insert into name_email set nombre='Fernando', email='fer@nando.com', cp = 4567;
insert into name_email set nombre='Noelia', email='noe@lia.com';
insert into name_email set nombre='Rosa', email='ro@sa.com', cp = 123513;
insert into name_email set nombre='Paula', email='pau@la.com';
insert into name_email set nombre='Adrián', email='adri@an.com', cp = 09876;
insert into name_email set nombre='Gary', email='gary@sheen.com';
insert into name_email set nombre='Lazlow', email='laz@low.com', cp = 23151;
insert into name_email set nombre='Marshall', email='mar@shall.com';
insert into name_email set nombre='Pedro', email='pe@dro.com', cp = 12345;
insert into name_email set nombre='boaemfaef', email='aiefam@sege.com';
insert into name_email set nombre='boaemfaef', email='aiefam@sege.com', cp = 15978;
insert into name_email set nombre='boaemfaef', email='aiefam@sege.com';
insert into name_email set nombre='boaemfaef', email='aiefam@sege.com', cp = 68453;
insert into name_email set nombre='boaemfaef', email='aiefam@sege.com';
insert into name_email set nombre='boaemfaef', email='aiefam@sege.com', cp = 19756;
insert into name_email set nombre='boaemfaef', email='aiefam@sege.com';
insert into name_email set nombre='boaemfaef', email='aiefam@sege.com', cp = 15686;
insert into name_email set nombre='boaemfaef', email='aiefam@sege.com';
insert into name_email set nombre='boaemfaef', email='aiefam@sege.com', cp = 13869;
insert into name_email set nombre='boaemfaef', email='aiefam@sege.com';
insert into name_email set nombre='boaemfaef', email='aiefam@sege.com', cp = 28695;
insert into name_email set nombre='boaemfaef', email='aiefam@sege.com';
insert into name_email set nombre='boaemfaef', email='aiefam@sege.com', cp = 28369;
insert into name_email set nombre='boaemfaef', email='aiefam@sege.com';